<?php

/**
 * @file
 * Scaffolding module for the "Islandora Development 101" workshop.
 */

/**
 * Implements hook_menu().
 */
function islandora_dev101_menu() {
  $items = array();
  $items['admin/islandora/tools/dev101'] = array(
    'title' => 'Islandora Development 101 Workshop module ',
    'description' => 'Configure the Islandora Dev101 module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_dev101_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Admin settings form builder.
 */
function islandora_dev101_admin_settings() {
  $form['islandora_dev101_message'] = array(
    '#title' => t('A message to write to log files, etc.'),
    '#type' => 'textfield',
    '#size' => 100,
    '#default_value' => variable_get('islandora_dev101_message', 'This just happened: '),
    '#description' => t("Text of a message we will use to demonstrate various things."),
    '#maxlength' => 255,
  );
  return system_settings_form($form);
}

/**
 * Implements hook_islandora_object_ingested().
 */
function islandora_dev101_islandora_object_ingested(AbstractObject $islandora_object) {
  // Do something.
}

/**
 * Implements hook_islandora_object_modified().
 */
function islandora_dev101_islandora_object_modified(AbstractObject $islandora_object) {
  // Do something.
}

/**
 * Implements hook_islandora_object_purged().
 */
function islandora_dev101_islandora_object_purged($pid) {
  // Do something.
}
